# Generated by Django 3.1.1 on 2020-10-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenDiaDiem', models.CharField(max_length=100)),
                ('giaGoc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('giaGiam', models.DecimalField(decimal_places=2, max_digits=20)),
                ('anhDiaDiem', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(max_length=100)),
                ('noiDung', models.TextField()),
                ('anhNen', models.ImageField(upload_to='')),
            ],
        ),
    ]
