# Generated by Django 3.1.1 on 2020-10-11 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(max_length=100)),
                ('gioiThieu', models.TextField()),
                ('anhDaiDien', models.ImageField(upload_to='')),
                ('twitter', models.TextField()),
                ('instagram', models.TextField()),
                ('facebook', models.TextField()),
            ],
        ),
    ]
