# Generated by Django 3.1.1 on 2020-09-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenDiaDiem', models.CharField(max_length=100)),
                ('giaGoc', models.DecimalField(decimal_places=2, max_digits=20)),
                ('giaGiam', models.DecimalField(decimal_places=2, max_digits=20)),
                ('anhDiaDiem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hoTen', models.CharField(max_length=100)),
                ('noiDung', models.TextField()),
                ('anhNen', models.TextField()),
            ],
        ),
    ]
