# Generated by Django 3.1.1 on 2020-09-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_discount_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='anhDiaDiem',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='anhNen',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='slide',
            name='anhNen',
            field=models.ImageField(upload_to=''),
        ),
    ]
